### ISSUE TITLE
Suggestion: adjust dusk/dawn schedule automatically depending on location

### ISSUE THREAD

**Issue by Ammako** [averne/Fizeau#25]
What the title says. Real life dusk/dawn time changes throughout the year, so it would be nice if the app could automatically set appropriate times based on your location, instead of having to manually adjust it all the time.

This should hopefully be doable offline by providing user coordinates, like redshift.

See: https://github.com/jonls/redshift

**Comment by averne** [comment]
Hello, that's an interesting suggestion but it would need to be implemented on the sysmodule side to be really useful (otherwise you'd need to open the application/overlay to update the values). 
Since it needs complicated logic and I'm trying to limit the code size of my binary (the memory pool reserved for sysmodules is really tight), I'm not going to implement it.
