### ISSUE TITLE
Fizeau 2.2.2 broken under ams 1.2.5

### ISSUE THREAD

**Issue by cucholix** [averne/Fizeau#42]
![fizeau_error](https://user-images.githubusercontent.com/16081693/144159401-564c9c73-694c-43f4-a6e0-ada96658b93c.jpg)
Just updated to 13.2.0|AMS 1.2.5|S 
Tested updating to Fizeau 2.2.3 no chainload, and the issue persist.

**Comment by averne** [comment]
Hello, I'm trying to fix/merge the [regio](https://github.com/averne/Fizeau/tree/regio) branch before making a new release. 
In the meantime, the CI builds should work since I pushed a change that should make it work regardless of the firmware version.
https://github.com/averne/Fizeau/suites/4497992234/artifacts/119996489

**Comment by FlyingBananaTree** [comment]
Just to let you know even with that commit it panics at boot on 13.2.0 until recompiled with the usual changes to the libstratosphere submodule, after which it's fine.

**Comment by averne** [comment]
> Just to let you know even with that commit it panics at boot on 13.2.0 until recompiled with the usual changes to the libstratosphere submodule, after which it's fine.

Yeah indeed, not sure why. I got tired of having to recompile every FW rev/AMS update, right now it *should* work in the future without needing an update (unless, of course, some breaking changes are introduced by nintendo/AMS).
