### ISSUE TITLE
Fails to start on 9.2.0

### ISSUE THREAD

**Issue by fennectech** [averne/Fizeau#5]
The sysmodule refuses to start on 9.2.0

**Comment by averne** [comment]
Works fine for me on 9.2.0/AMS 0.10.3. 
Can you try verifying your setup/disabling other sysmodules, and get back to me with more info?

**Comment by fennectech** [comment]
Ive tried disabling so only Filza was running (well. Enabled. It didn’t start. It just turns on then goes off)    Same result.  I also deleted its config file in /switch

**Comment by fennectech** [comment]
It cant be started if Tesla has run before   You cant kill Tesla and then start this. But you can disable Tesla. Reboot then start this. You can start Tesla after that but appear.

**Comment by averne** [comment]
Do you know if Fizeau/Tesla exhibited the same behavior on previous firmware versions? 
Fwiw I'm pretty sure it fails at creating a managed layer because of a resource limit or something similar.

**Comment by fennectech** [comment]
I dont think i had issues but I’m not 100 percent

**Comment by averne** [comment]
So tesla and Fizeau use the same way to display stuff on top of everything (managed layers). However, it's only possible to have one of those up at a time. Therefore, using tesla and Fizeau at the same time is not possible.
Instead, I now properly close my layer on deactivation so that tesla can create its own.
So to use tesla, you need to deactivate Fizeau first (press the "Overlay active" checkbox).
I know it's not ideal, but that's as far as I can go.
