### ISSUE TITLE
Some minor issues/bugs with Fizeau

### ISSUE THREAD

**Issue by monstrosities** [averne/Fizeau#50]
I would like to report a few issues/bugs with the latest version of Fizeau. I am not sure if these are expected or even resolvable but thought they were worth mentioning in case something was missed. I am sorry if some of the details are a bit vague.

I am using the actions build https://github.com/averne/Fizeau/actions/runs/2036835490 to be able to use Fizeau on current firmware and I have been using the latest atmosphere and latest official firmware.

The first issue is that any type of reboot or shutdown takes around 10 seconds if Fizeau is running instead of being more or less instant as it is normally.

The second issue is a little more vague but I found that if Fizeau is running the Tesla sysmodule and even some homebrew experience data aborts more frequently which cause atmosphere to crash. The main one I come across is when frequently opening and closing a Tesla overlay to use its functions, I usually experience this with the emuiibo overlay for example.

Thank you!

**Comment by averne** [comment]
The first issue should have been fixed with this build.
[Fizeau-2.3.1-25141ac.zip](https://github.com/averne/Fizeau/files/9909935/Fizeau-2.3.1-25141ac.zip)
[Fizeau-chl-2.3.1-25141ac.zip](https://github.com/averne/Fizeau/files/9909937/Fizeau-chl-2.3.1-25141ac.zip)
As for the second I haven't noticed increased instability personally, I'm tempted to believe it's placebo consider I don't really see a way this sysmodule could affect other code. Is there particular homebrew that's more prone to crashing?

**Comment by monstrosities** [comment]
Apologies, I didn't see this message until the new release just happened.

Thanks for that bug fix. As for the second part it's been a long time but the crashes seem to be more of a Tesla issue that occurs in docked mode. If there's anything that seems specific to Fizeau I'll comment again or open an issue if that's ok with you.

**Comment by averne** [comment]
Thanks for the heads up
