### ISSUE TITLE
Crash in sleep mode

### ISSUE THREAD

**Issue by Mastergaming1x** [averne/Fizeau#58]
When I leave my switch in sleep mode, it would crash atmosphere. When I move the content folder on my SD card, it would fix it.

**Comment by averne** [comment]
Can you please upload the error report

**Comment by theimpatientsamurai** [comment]
I want to try to explain as best I can so this issue can get fixed for me and others:

The error is related to sleep mode, which works properly out of dock, and in dock mode, but as soon as I pull it out of the dock, it 100% chance crashes. I deleted all mods and it functions properly. I tried this and Tesla as the only thing in the Atmosphere/contents folder, and deleted all other ovl's, and it occurs 100% of the time, so it has to be because of this HB program. It's not Tesla, as it works just fine by itself, and alongside all other HB I have.

Switch is original 2017 model, low serial, no modchip.
FW Version is 16.0.2, but it also occurred on 15.0.0
Atmosphere is current (1.5.2)
Hekate is current: (6.0.3)

Nothing else should be interfering with it on the switch; there are no other modules or Atmosphere mods enabled/installed.
Hopefully we can get to the bottom of this, as it makes it hard to swap between docked and handheld play.
