### ISSUE TITLE
Fizeau 2.4.1 Not working on HOS 16.0.1 - AMS 1.5.1

### ISSUE THREAD

**Issue by letoroui** [averne/Fizeau#61]
Getting error: 0x1 (2001-0000)

**Comment by averne** [comment]
It means that the background service is not running. Please check that the files are correctly installed, and run the hekate archive fit fixer.

**Comment by slugger6703** [comment]
still isn't working and getting the same error  0x1 (2001-0000)

**Comment by appleforever11** [comment]
Same issue here. Any fix yet?

**Comment by averne** [comment]
Hi, the app works on my console with the same configuration.
So unfortunately, until someone gives me actionnable information, I can only assume user error.
Please check:
- That the files are correctly installed
- That the archive bit isn't set on the atmosphere folder (run the hekate archive bit fixer)

Failing that, there should be an error report being generated, as the service failed to launch. Please upload it here so that I can check it.

**Comment by averne** [comment]
Tested working on up to 17.0
