### ISSUE TITLE
Brightness setting missing?

### ISSUE THREAD

**Issue by VorgonBattlecruiser** [averne/Fizeau#85]
updated my switch lite to the current version and wanted to replicate some of the settings given online but im missing the "brightness" setting?
what am i doing wrong?

**Comment by averne** [comment]
Brightness control has been unavailable for close to 2 years, due to internal changes in the OS. The parameter then did nothing, and consequently I decided to remove it. So you're not doing anything wrong, and you can remove that value. 
Do note that "brightness" controlled the backlight setting. You can still adjust the color luminance, which helps further dimming the screen when playing in the dark, for instance.

**Comment by Cooler3Ds** [comment]
> Brightness control has been unavailable for close to 2 years, due to internal changes in the OS. The parameter then did nothing, and consequently I decided to remove it. So you're not doing anything wrong, and you can remove that value. Do note that "brightness" controlled the backlight setting. You can still adjust the color luminance, which helps further dimming the screen when playing in the dark, for instance.

Hello. Thanks for the development.
Backlight brightness can be controlled via:
result lblSetCurrentBrightnessSetting(float brightness);
from libnx. I use this function in my system module, it works without any complaints.

**Comment by averne** [comment]
> > Brightness control has been unavailable for close to 2 years, due to internal changes in the OS. The parameter then did nothing, and consequently I decided to remove it. So you're not doing anything wrong, and you can remove that value. Do note that "brightness" controlled the backlight setting. You can still adjust the color luminance, which helps further dimming the screen when playing in the dark, for instance.
> 
> Hello. Thanks for the development.
> Backlight brightness can be controlled via:
> result lblSetCurrentBrightnessSetting(float brightness);
> from libnx. I use this function in my system module, it works without any complaints.
> 

This is what Fizeau was using before a system update changed the number of available sessions for the lbl service. If I recall correctly, the fatal sysmodule will fail to initialize its own session and panic. So in effect, this rendered the fatal module useless.

Maybe the situation has changed since then. I'm personally not interested in this feature, but if you're willing to perform the research, patches are welcome.
